### ISSUE TITLE
~ to close console adds character

### ISSUE THREAD

**Issue by celeronpm** [LukaszKr/PowerConsole#1]
Pressing ~ to close console adds a ~ to the console textbox. But upon pressing ~ again to bring it up once more, the last ~ is there. This means you have to press backspace to delete the last ~ otherwise the commands have ~ appended to them.

If you open, close the console using ~ multiple times, it just keeps adding more ~ to the textbox.

**Comment by LukaszKr** [comment]
Hey thanks for the report. I've pushed a fix for the issue. TextField was still focused after console was closed. There might be some hidden input layer in GUI, as '~' that was added, was reported with KeyCode equal to None in Event, when I've tried to consume it.

**Comment by LukaszKr** [comment]
Nice to hear that, I'm glad you like it.
