### ISSUE TITLE
Parsing issues in console (negative floats)

### ISSUE THREAD

**Issue by rotolonico** [LukaszKr/PowerConsole#2]
I'd like to type a command in the console that has a float value as a parameter. Whenever I try to set a negative float though, the command will not run and there will be an exception:

`NullReferenceException: Object reference not set to an instance of an object
ProceduralLevel.PowerConsole.Logic.ConsoleInstance.Execute (System.Collections.Generic.List`1[T] queries) (at Assets/Plugins/ProceduralLevel/PowerConsole/Code/Logic/ConsoleInstance.cs:134)
ProceduralLevel.PowerConsole.Logic.ConsoleInstance.Execute (System.String strQuery, System.Boolean recordHistory) (at Assets/Plugins/ProceduralLevel/PowerConsole/Code/Logic/ConsoleInstance.cs:111)
ProceduralLevel.PowerConsole.Logic.InputModule.Execute () (at Assets/Plugins/ProceduralLevel/PowerConsole/Code/Logic/Module/InputModule.cs:78)
ProceduralLevel.PowerConsole.View.ConsoleInput.TryInvoke (UnityEngine.KeyCode[] keys, System.Action action) (at Assets/Plugins/ProceduralLevel/PowerConsole/Code/View/Input/ConsoleInput.cs:46)
ProceduralLevel.PowerConsole.View.ConsoleInput.Update () (at Assets/Plugins/ProceduralLevel/PowerConsole/Code/View/Input/ConsoleInput.cs:38)
ProceduralLevel.PowerConsole.View.ConsoleView.OnGUI () (at Assets/Plugins/ProceduralLevel/PowerConsole/Code/View/ConsoleView.cs:47)
`

The command I used:
`commandName -5`

**Comment by LukaszKr** [comment]
There was an issue with negative number, that they were completely not supported, thank you for pointing that out.
I've pushed 2 commits that are addressing this and few fixes related to options parsing throwing null exceptions in few more places. Also added a test for that!

**Comment by rotolonico** [comment]
Thank you so much, this solved my problem!
I just wanted to note that, if you hit tab while the caret is on "-", it will autocomplete the next command at the beginning of the line instead of autocompleting the integer value.
