### ISSUE TITLE
All floats are parsed negative after first one

### ISSUE THREAD

**Issue by rotolonico** [LukaszKr/PowerConsole#3]
Very specific bug, but basically if you create a command that has two floats as parameters if you set the first one to negative, the second one will also be negative no matter what.

Example command spawnobject(int posX, int posY)
Console: spawnobject -50 100
// Object spawns at -50 -100 instead of spawning at -50 100

**Comment by LukaszKr** [comment]
Should be fixed in newest.
Also fixed issue with hint iteration for negative numbers that you have mentioned in here:
https://github.com/LukaszKr/PowerConsole/issues/2

**Comment by rotolonico** [comment]
Great!
