### ISSUE TITLE
Can't parse strings with spaces and '-'

### ISSUE THREAD

**Issue by rotolonico** [LukaszKr/PowerConsole#5]
Is there any way to parse strings that contain spaces and the '-' character when typing the command in the console?

**Comment by LukaszKr** [comment]
Currently only by adding quotes around that string, which means no '-' as a parameter, command or option name. 
Though this is a bug that will be fixed, as a space before '-' should be required for it to be treated as special token.

**Comment by LukaszKr** [comment]
https://github.com/LukaszKr/PowerConsole/commit/bc4e0fef9c815b77c9b1812b54fc48370ed26bc3 - will fix the issue and you should be now able to use dash inside a string without quotes.
